# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            veronica nutting
tagline:          'veronica nutting'
description:      'my personal website'
url:              https://veronicanutting.github.io
baseurl:          '/vin'

author:
  name:           'Veronica Nutting'
  url:            https://www.linkedin.com/in/veronicanutting/

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
#sidebar_home_link:  true
